export type DataT = {
  id: number;
  name: string;
  Company: string;
  PhoneNumber: string;
  Email: string;
  Country: string;
  Status: boolean;
};

export const data = [
  {
    id: 1,
    name: "Jane Cooper1",
    Company: "Microsoft",
    PhoneNumber: "(255) 555 1118",
    Email: "jane@microsoft.com",
    Country: "United States",
    Status: true,
  },
  {
    id: 2,
    name: "Floyd Cooper2",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 3,
    name: "Jane Cooper3",
    Company: "Microsoft",
    PhoneNumber: "(255) 555 1118",
    Email: "jane@microsoft.com",
    Country: "United States",
    Status: true,
  },
  {
    id: 4,
    name: "Floyd Cooper4",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 5,
    name: "Jane Cooper5",
    Company: "Microsoft",
    PhoneNumber: "(255) 555 1118",
    Email: "jane@microsoft.com",
    Country: "United States",
    Status: true,
  },
  {
    id: 6,
    name: "Floyd Cooper6",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 7,
    name: "Jane Cooper7",
    Company: "Microsoft",
    PhoneNumber: "(255) 555 1118",
    Email: "jane@microsoft.com",
    Country: "United States",
    Status: true,
  },
  {
    id: 8,
    name: "Floyd Cooper8",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 9,
    name: "Jane Cooper9",
    Company: "Microsoft",
    PhoneNumber: "(255) 555 1118",
    Email: "jane@microsoft.com",
    Country: "United States",
    Status: true,
  },
  {
    id: 10,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 11,
    name: "Jane Cooper",
    Company: "Microsoft",
    PhoneNumber: "(255) 555 1118",
    Email: "jane@microsoft.com",
    Country: "United States",
    Status: true,
  },
  {
    id: 12,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 13,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 14,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 15,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 16,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 17,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 18,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 19,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 20,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 21,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 22,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 23,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 24,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 25,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
  {
    id: 26,
    name: "Floyd Cooper",
    Company: "Yahoo",
    PhoneNumber: "(205) 555 0100",
    Email: "floyd@yahoo.com",
    Country: "Kiribati",
    Status: false,
  },
];
